config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'sessions#new'
  # users
  get 'sign_up', to: 'users#new'
  post 'sign_up', to: 'users#create'
  resources :users, only: %i[index show edit create update]
  # sessions
  get '/sign_in', to: 'sessions#new'
  post '/sign_in', to: 'sessions#create'
  post '/sign_out', to: 'sessions#destroy'
  get '/sign_out', to: 'sessions#destroy'
  # blogposts
  resources :blog_posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
# frozen_string_literal: true

# model for blog_posts db table
class BlogPost < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar

  validates :subject, presence: true
  validates :description, presence: true
end

app/models/role.rb
# frozen_string_literal: true

# Role representation
class Role < ApplicationRecord
  ADMIN = 'admin'
  MEMBER = 'member'
  VALID_ROLES = [ADMIN, MEMBER].freeze

  belongs_to :user

  validates :name, inclusion: { in: VALID_ROLES, message: '%<value>s is not a valid role' }
end

app/models/user.rb
# frozen_string_literal: true

# User representation
class User < ApplicationRecord
  # adds virtual attributes for authentication
  has_secure_password
  has_many :roles
  has_one_attached :avatar

  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }

  def role_names=(roles)
    roles.split('|').reject(&:empty?).each do |role|
      ::Role.create!(name: role, user_id: id)
    end
  end

  def role_names
    roles.empty? ? '' : "|#{roles.pluck(:name).join('|')}|"
  end

  def add_role(role)
    roles.create!(name: role.to_s)
  end

  def remove_role(role)
    roles.find_by(name: role.to_s).delete
    reload
  end

  def admin?
    roles.pluck(:name).include?(::Role::ADMIN)
  end

  def member?
    roles.pluck(:name).include?(::Role::MEMBER)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# application controller
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def ensure_user_session
    unauthorized unless logged_in?
  end
end

app/controllers/blog_posts_controller.rb
# frozen_string_literal: true

# controller of blog posts
class BlogPostsController < ApplicationController
  before_action :find_blog_post_for_create, only: %i[create]
  before_action :find_blog_post, only: %i[show edit update]
  before_action :ensure_user_session

  def index
    @blog_posts = BlogPost.all
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    if @blog_post.save
      redirect_to blog_post_path(@blog_post)
      flash[:success] = 'Successfully created post!'
    else
      render :new
      flash[:danger] = @blog_post.errors.full_messages.join(', ')
    end
  end

  def show; end

  def edit; end

  def update
    if @blog_post.update(blogpost_params)
      flash[:success] = 'Successfully updated post!'
      redirect_to blog_post_path(@blog_post)
    else
      redirect_to edit_blog_post_path(@blog_post)
      flash[:danger] = @blog_post.errors.full_messages.join(', ')
    end
  end

  private

  def find_blog_post_for_create
    @blog_post = ::BlogPost.new(blogpost_params.merge(user: current_user))
  end

  def find_blog_post
    @blog_post = ::BlogPost.find(params[:id])
  end

  def blogpost_params
    params.require(:blog_post).permit(:subject, :description, :avatar)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# controls user session requests
class SessionsController < ApplicationController
  before_action :load_user, only: %i[create]

  def new; end

  def create
    if !!@user && @user.authenticate(params[:password])
      sign_in(@user)
      flash[:success] = 'Successfully signed in!'
      redirect_to(user_path(@user))
    else
      flash[:danger] = 'Provided credentials not recognized. Please try again or register below.'
      redirect_to(sign_in_path)
    end
  end

  def destroy
    sign_out
    flash[:success] = 'Successfully signed out!'
    redirect_to(root_path)
  end

  private

  def load_user
    @user = ::User.find_by(email: params[:email])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Controls requests around User
class UsersController < ApplicationController
  before_action :load_user_for_create, only: %i[create]
  before_action :load_user, only: %i[show edit update]
  before_action :ensure_user_session, except: %i[new create]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
      flash[:success] = 'Successfully created account'
    else
      redirect_to sign_up_path
      flash[:danger] = @user.errors.full_messages.join(', ')
    end
  end

  def show
    @user = @user.decorate
  end

  def edit
    @user = @user.decorate
  end

  def update
    handle_role_names

    if @user.update(user_params)
      flash[:success] = 'Successfully updated user'
      redirect_to user_path(@user)
    else
      redirect_to edit_user_path(@user)
      flash[:danger] = @user.errors.full_messages.join(', ')
    end
  end

  private

  def handle_role_names
    return nil unless roles_changed?

    roles = params[:user][:role_names].reject(&:empty?)

    @user.roles.each { |role| @user.remove_role(role.name) } if roles.present?
    roles.each { |role| @user.add_role(role.downcase) }
  end

  def roles_changed?
    role_names_in_params = params[:user][:role_names].reject(&:empty?)
    stored_role_names = @user.decorate.formatted_role_names.split(',')

    role_names_in_params != stored_role_names
  end

  def load_user_for_create
    @user = User.new(user_params)
  end

  def load_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :role_names, :password, :password_confirmation, :avatar)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# application helper
module ApplicationHelper
  def logged_in?
    !!session[:user_id]
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if logged_in?
  end
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

# sessions helper
module SessionsHelper
  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def unauthorized
    flash[:danger] = 'You do not have permission to access this page'
    redirect_to root_path
  end
end

app/views/blog_posts/edit.html.slim
.container.py-4
  section.py-5.text-center.container
    .row.py-lg-5
      .col-lg-6.col-md-8.mx-auto
        h1.fw-light= 'Edit Post'

  .row.g-5
    .col-md-2
    .col-md-8
      = form_for @blog_post, local: true, html: { id: 'edit_blog_post_form' } do |f|
        .row.g-3
          .col-12
            = f.label :subject, class: 'form-label'
            = f.text_field :subject, class: 'form-control'
            .invalid-feedback= 'Valid subject is required'
          .col-12
            = f.label 'Image', class: 'form-label'
            = f.file_field :avatar, class: 'form-control'
          .col-12
            = f.label :description, class: 'form-label'
            = f.text_area :description, rows: 3, class: 'form-control'
            .invalid-feedback= 'Vaid description is required'
        hr.my-4
        ul.nav.justify-content-end
          li.nav-item
            = link_to 'Back', :back, class: 'btn btn-outline-primary me-2'
          li.nav-item
            = f.submit 'Update Post', class: 'btn btn-primary'

    .col-md-2

app/views/blog_posts/index.html.slim
.container.py-4
  section.py-5.text-center.container
    .row.py-lg-5
      .col-lg-6.col-md-8.mx-auto
        h1.fw-light= 'All Posts'
        p.lead.text-muted= 'Create a new blog post'
        = link_to 'New Post', new_blog_post_path, class: 'btn btn-primary my-2'

  .album.py-5.bg-light
    .container
      .row.row-cols-3.row-cols-md-3.g-4
        - @blog_posts.each do |b|
          .col
            .card.shadow-sm.h-100
              .card-header=b.subject
              - if b.avatar.attached?
                .text-center
                  img.card-img-top src="#{url_for(b.avatar)}" width='50%'
              - else
                svg class='bd-placeholder-img card-img-top' width='100%' height='355' xmlns='http://www.w3.org/2000/svg' role='img' aria-label='Placeholder: Thumbnail'
                  title= 'Placeholder'
                  rect width='100%' height='100%' fill='#55595c'
                  text x='50%' y='50%' fill='#eceeef' dy='.3em'
              .card-body
                p.card-text=b.description
                .d-flex.justify-content-between.align-items-center
                  .btn-group
                    = link_to 'View', blog_post_path(b), class: 'btn btn-sm btn-outline-secondary'
                    = link_to 'Edit', edit_blog_post_path(b), class: 'btn btn-sm btn-outline-secondary'
              .card-footer
                small.text-muted= "Created #{time_ago_in_words(b.created_at)} ago by #{b.user.email}"

  br
  nav aria-label="Pagination"

app/views/blog_posts/new.html.slim
.container.py-4
  section.py-5.text-center.container
    .row.py-lg-5
      .col-lg-6.col-md-8.mx-auto
        h1.fw-light= 'New Post'

  .row.g-5
    .col-md-2
    .col-md-8
      = form_for @blog_post do |f|
        .row.g-3
          .col-12
            = f.label :subject, class: 'form-label'
            = f.text_field :subject, class: 'form-control', placeholder: 'Enter subject', required: true
            .invalid-feedback= 'Valid subject is required'
          .col-12
            = f.label :description, class: 'form-label'
            = f.text_area :description, rows: 3, class: 'form-control', required: true
            .invalid-feedback= 'Valid description is required'
          .col-12
            = f.label 'Image', class: 'form-label'
            = f.file_field :avatar, class: 'form-control'
          .col-12
        .my-4
        ul.nav.justify-content-end
          li.nav-item
            = link_to 'Back', :back, class: 'btn btn-outline-primary me-2'
          li.nav-item
            = f.submit 'Create Post', class: 'btn btn-primary'
    .col-md-2

app/views/blog_posts/show.html.slim
.container
  .row.g-5
    .col-md-8
      article.blog-post
        h2.blog-post-title=@blog_post.subject.titleize
        p.blog-post-meta="#{@blog_post.created_at.strftime('%b %d, %Y')} by #{@blog_post.user.email}"
        hr
        - if @blog_post.avatar.attached?
          .text-center
            img src="#{url_for(@blog_post.avatar)}" width='50%' height='50%'
        p.mb-4=@blog_post.description
      nav.blog-pagination aria-label="Pagination"
        = link_to 'Edit', edit_blog_post_path(@blog_post), class: 'btn btn-outline-primary'
    .col-md-4
      .position-sticky style="top: 2rem;"
        .p-4.mb-3.bg-light.rounded
          h4.fst-italic About
          p.mb-0 Test

app/views/layouts/application.html.slim
doctype html
html
  head
    title Myapp
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_include_tag "application", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"

  body
    .container
      - flash.each do |type, msg|
        div class="alert alert-#{type}"
          = msg

    header.p-3.mb-3.border-bottom
      .container
        header.d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-lg-start
          ul.nav.col-12.col-lg-auto.me-lg-auto.mb-2.justify-content-center.mb-md-0
            li
              = link_to 'Home', root_path, class: 'nav-link px-2 link-secondary'
            - if current_user.present?
              li
                = link_to 'Posts', blog_posts_path, class: 'nav-link px-2 link-dark'
          form.col-12.col-lg-auto.mb-3.mb-lg-0.me-lg-3
            input type='search' class='form-control' placeholder='Search...' aria-label='Search'
          - unless logged_in?
            div
              = link_to 'Login', sign_in_path, class: 'btn btn-outline-primary me-2'
              = link_to 'Sign-up', sign_up_path, class: 'btn btn-primary'
          - else
            div.text-end
              a href='#' class='d-block link-dark text-decoration-none dropdown-toggle' id='dropdownUser1' data-bs-toggle='dropdown' aria-expanded='false'
                - if current_user.avatar.attached?
                  image src="#{url_for(current_user.avatar)}" width='32' height='32' class='rounded-circle'
                - else
                  image src='' width='32' height='32' class='rounded-circle'
              ul.dropdown-menu.text-small aria-labelledby='dropdownUser1'
                li
                  = link_to 'My Profile', user_path(current_user.id), class: 'dropdown-item'
                li
                  = link_to 'Sign out', sign_out_path, class: 'dropdown-item'

    = yield

app/views/users/edit.html.slim
.container.py-4
  section.py-5.text-center.container
    .row.py-lg-5
      .col-lg-6.col-md-8.mx-auto
        h1.fw-light= 'Edit User'

  .row.g-5
    .col-md-2
    .col-md-8
      = form_for @user, local: true, html: { id: 'edit_user_form' } do |f|
        .row.g-3
          .col-12
            = f.label :email, { class: 'form-label' }
            = f.text_field :email, { class: 'form-control' }
          .col-12
            = f.label :role_names, { class: 'form-label' }
            = f.select :role_names, options_for_select(::Role::VALID_ROLES.map { |role| role.titleize}), { include_blank: false }, { multiple: true, size: ::Role::VALID_ROLES.size, class: 'form-control selectpicker' }
          .col-12
            = f.label 'Profile Photo', class: 'form-label'
            = f.file_field :avatar, class: 'form-control'
          .col-6
            = f.label :password, { class: 'form-label' }
            = f.password_field :password, { class: 'form-control' }
          .col-6
            = f.label :password_confirmation, { class: 'form-label' }
            = f.password_field :password_confirmation, { class: 'form-control' }
        .my-4
        ul.nav.justify-content-end
          li.nav-item
            = link_to 'Back', :back, class: 'btn btn-outline-primary me-2'
          li.nav-item
            = f.submit 'Update', class: 'btn btn-primary'


    .col-md-2

app/views/users/index.html.slim
.container-sm
  section.jumbotron.text-center.mt-3.mb-5
    h3 Users

  .mb-3.row
    .d-grid.gap-2.d-md-flex.justify-content-md-end
      = link_to 'New User', sign_up_path, class: 'btn btn-primary justify-content-end'
  .col-md-3
  .col-md-6
  form
    .card
      .card-body
        .mb-3.row
          .col-md-12
            table.table.table-striped.table-bordered
              thead.thead-light
                tr
                  th ID
                  th Email
                  th Actions
              tbody
                - @users.each do |u|
                  tr
                    td= link_to u.id, user_path(u)
                    td= u.email
                    td
                      = link_to 'Edit', edit_user_path(u), class: 'btn btn-outline-primary btn-sm'
  .col-md-3

app/views/users/new.html.slim
.container-sm
  .row.align-items-start
    section.jumbotron.text-center
      h3 Register
      p Please fill in this form to register an account

    .col-md-3
    .col-md-6
      = form_with model: @user, url: sign_up_path do |f|
        .card
          .card-body
            .mb-3.row
              .col-md-12
                = f.label :email, class: 'form-label'
                = f.text_field :email, class: 'form-control', placeholder: 'Enter email', required: true
            .mb-3.row
              .col-md-6
                = f.label :password, class: 'form-label'
                = f.password_field :password, class: 'form-control', placeholder: 'Enter password', required: true
              .col-md-6
                = f.label :password_confirmation, class: 'form-label'
                = f.password_field :password_confirmation, class: 'form-control', placeholder: 'Re-enter password', required: true
            .mb-3.row
              .col-md-12
                = f.submit 'Sign up', { class: 'btn btn-primary btn-sm btn-block' }

    .col-md-3

app/views/users/show.html.slim
.container.py-4
  section.py-5.text-center.container
    .row
      .col-lg-6.col-md-8.mx-auto
        h1.fw-light User

  .row.g-5
    .col-md-3
    .col-md-6
      article.blog-post
        - if @user.avatar.attached?
          .text-center
            img src="#{url_for(@user.avatar)}" width="25%" heigth="50%"
          br
        table.table.table-striped.table-bordered
          thead.thead-light
          tbody
            tr
              th Email
              td= @user.email
            tr
              th Roles
              td= @user.formatted_role_names
      ul.nav.justify-content-end
        li.nav-item
          = link_to 'Back', :back, class: 'btn btn-outline-primary me-2'
        li.nav-item
          = link_to 'Edit', edit_user_path(@user), class: 'btn btn-primary'
    .col-md-3